### ISSUE TITLE
似乎新的chrome cookie获取方法变了？

### ISSUE THREAD

**Issue by GarretRen** [wgzeyu/ExDownloader#2]
我重新下载了个5.4版本，用F12获取到的cookie不能被识别，说是格式错误。

我的cookie长这样：
__cfduid=d68d7feb371a0f78d343f2d90f10f221f1541823968; sl=dm_1

**Comment by GarretRen** [comment]
F12 之后在这一步我卡住了，我试的copy as curl
![default](https://user-images.githubusercontent.com/31581037/48993423-8d12f700-f178-11e8-8288-f7bc31045a3e.png

**Comment by GarretRen** [comment]
之前你有个视频教学，结果现在我没找到那个选项……

**Comment by wgzeyu** [comment]
Copy as cURL
找到以下字段：
"Cookie: 内容"
复制cookie内容（不含Cookie:与引号）

**Comment by GarretRen** [comment]
Copy as cURL(cmd)内容如下：

curl "https://e-hentai.org/" -H "authority: e-hentai.org" -H "cache-control: max-age=0" -H "upgrade-insecure-requests: 1" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "referer: https://e-hentai.org/g/1320066/f1ec315e5a/" -H "accept-encoding: gzip, deflate, br" -H "accept-language: zh-CN,zh;q=0.9" -H "cookie: __cfduid=d68d7feb371a0f78d343f2d90f10f221f1541823968; sl=dm_1" --compressed

我尝试cookie后面的：
__cfduid=d68d7feb371a0f78d343f2d90f10f221f1541823968; sl=dm_1" --compressed
显示格式错误

**Comment by wgzeyu** [comment]
你是不是没有登录？

**Comment by wgzeyu** [comment]
实际上不只是需要去掉--compressed，引号开始后面的都要去掉

**Comment by GarretRen** [comment]
确实是我没登录，问题解决了，谢谢
